### ISSUE TITLE
安装这个插件后，YAPI打不开了，怎么办，卸载也没用

### ISSUE THREAD

**Issue by ZYG-Test** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#17]
![image](https://user-images.githubusercontent.com/42433638/82853954-ad706d00-9f39-11ea-84a1-ca00f8e2fe5f.png)

**Comment by shouldnotappearcalm** [comment]
命令安装的还是容器里面

**Comment by ZYG-Test** [comment]
命令安装的。非常感谢帮我解答，这个问题我没描述清楚，我重新描述一下

1、我在安装时，提示错误，错误信息如下：
`正在下载插件...
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^1.2.3`": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-26T07_50_31_730Z-debug.log
更新插件成功
正在安装依赖...
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^1.2.3`": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-26T07_50_39_054Z-debug.log
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
/tmp/shelljs_d42c08a61a1fbadd93dc:10
    fs.writeFileSync(fname, err.code.toString());
                                     ^

TypeError: Cannot read property 'toString' of null
    at /tmp/shelljs_d42c08a61a1fbadd93dc:10:38
    at ChildProcess.exithandler (child_process.js:288:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
exec: internal error
编译客户端成功，请重启服务器`


2、然后我在打开yapi就打不开了，查看开发者工具，发现/prd/assets.js?v=0.21085413605511305报404，执行卸载插件的命令后还是报错。

`11:11 GET http://129.204.67.227:3000/prd/assets.js?v=0.21085413605511305 net::ERR_ABORTED 404 (Not Found)
(anonymous) @ 11:11
11:15 Uncaught TypeError: Cannot read property 'index.js' of undefined
    at 11:15
(anonymous) @ 11:15
11:24 Uncaught TypeError: Cannot read property 'manifest' of undefined
    at 11:24
(anonymous) @ 11:24
11:27 Uncaught TypeError: Cannot read property 'lib3' of undefined
    at 11:27
(anonymous) @ 11:27
11:30 Uncaught TypeError: Cannot read property 'lib2' of undefined
    at 11:30
(anonymous) @ 11:30
11:33 Uncaught TypeError: Cannot read property 'lib' of undefined
    at 11:33
(anonymous) @ 11:33
11:37 Uncaught TypeError: Cannot read property 'index.js' of undefined
    at 11:37`

**Comment by shouldnotappearcalm** [comment]
你卸载了之后 `npm run build`

**Comment by PerezYuan** [comment]
> 你卸载了之后 `npm run build`

package.json 没有build的script ，我也有这个问题，能解决吗？
