### ISSUE TITLE
插件安装过程中报了很多错误，但是提示编译客户端成功，请问是安装成功了吗

### ISSUE THREAD

**Issue by Marvincool** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#18]
下面是错误信息，报了一堆错，不敢重启了。
```bash
[root@ my-yapi]# yapi plugin --name yapi-plugin-interface-oauth2-token
需要安装 ykit
[root@ my-yapi]# npm install ykit -g
npm WARN deprecated extract-text-webpack-plugin@1.0.1: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated ejs@2.3.4: Critical security bugs fixed in 2.5.5
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
/home/node-install/node-v13.0.1-linux-x64/bin/ykit -> /home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/bin/ykit

> core-js@2.6.11 postinstall /home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> history@1.17.0 postinstall /home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/node_modules/history
> node ./npm-scripts/postinstall.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/ykit/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN follow-redirects@1.12.0 requires a peer of debug@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

+ ykit@0.8.13
added 802 packages from 608 contributors in 249.85s
[root@ my-yapi]# yapi plugin --name yapi-plugin-interface-oauth2-token
正在下载插件...
npm WARN deprecated extract-text-webpack-plugin@1.0.1: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin

> ghooks@2.0.4 install /root/mongodb/my-yapi/vendors/node_modules/ghooks
> node ./bin/module-install

This does not seem to be a git project.
Although ghooks was installed, the actual git hooks have not.
Run "git init" and then "npm explore ghooks -- npm run install".

Please ignore this message if you are not using ghooks directly.

> node-sass@4.14.1 install /root/mongodb/my-yapi/vendors/node_modules/node-sass
> node scripts/install.js

Unable to save binary /root/mongodb/my-yapi/vendors/node_modules/node-sass/vendor/linux-x64-79 : Error: EACCES: permission denied, mkdir '/root/mongodb/my-yapi/vendors/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:839:3)
    at sync (/root/mongodb/my-yapi/vendors/node_modules/mkdirp/index.js:72:13)
    at Function.sync (/root/mongodb/my-yapi/vendors/node_modules/mkdirp/index.js:78:24)
    at checkAndDownloadBinary (/root/mongodb/my-yapi/vendors/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/root/mongodb/my-yapi/vendors/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/mongodb/my-yapi/vendors/node_modules/node-sass/vendor'
}

> core-js-pure@3.6.5 postinstall /root/mongodb/my-yapi/vendors/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> history@1.17.0 postinstall /root/mongodb/my-yapi/vendors/node_modules/jerryproxy-ykit/node_modules/history
> node ./npm-scripts/postinstall.js


> react-slick@0.17.1 postinstall /root/mongodb/my-yapi/vendors/node_modules/react-slick
> opencollective postinstall


     *** Thank you for using react-slick! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/react-slick/donate

                    ***


> node-sass@4.14.1 postinstall /root/mongodb/my-yapi/vendors/node_modules/node-sass
> node scripts/build.js

Building: /home/node-install/node-v13.0.1-linux-x64/bin/node /root/mongodb/my-yapi/vendors/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/node-install/node-v13.0.1-linux-x64/bin/node',
gyp verb cli   '/root/mongodb/my-yapi/vendors/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.0.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.5
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 13.0.1
gyp verb command install [ '13.0.1' ]
gyp verb install input version string "13.0.1"
gyp verb install installing version: 13.0.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 13.0.1
gyp verb ensuring nodedir is created /root/.node-gyp/13.0.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/13.0.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '13.0.1' ]
gyp verb install input version string "13.0.1"
gyp verb install installing version: 13.0.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 13.0.1
gyp verb ensuring nodedir is created /root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp/13.0.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '13.0.1' ]
gyp verb remove using node-gyp dir: /root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 13.0.1
gyp verb remove removing development files for version: 13.0.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '13.0.1' ]
gyp verb remove using node-gyp dir: /root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 13.0.1
gyp verb remove removing development files for version: 13.0.1
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 3.10.0-1062.1.1.el7.x86_64
gyp ERR! command "/home/node-install/node-v13.0.1-linux-x64/bin/node" "/root/mongodb/my-yapi/vendors/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/mongodb/my-yapi/vendors/node_modules/node-sass
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-17T09_42_09_722Z-debug.log
安装插件成功
正在安装依赖...

> node-sass@4.14.1 install /root/mongodb/my-yapi/vendors/node_modules/node-sass
> node scripts/install.js

Unable to save binary /root/mongodb/my-yapi/vendors/node_modules/node-sass/vendor/linux-x64-79 : Error: EACCES: permission denied, mkdir '/root/mongodb/my-yapi/vendors/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:839:3)
    at sync (/root/mongodb/my-yapi/vendors/node_modules/mkdirp/index.js:72:13)
    at Function.sync (/root/mongodb/my-yapi/vendors/node_modules/mkdirp/index.js:78:24)
    at checkAndDownloadBinary (/root/mongodb/my-yapi/vendors/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/root/mongodb/my-yapi/vendors/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/root/mongodb/my-yapi/vendors/node_modules/node-sass/vendor'
}

> node-sass@4.14.1 postinstall /root/mongodb/my-yapi/vendors/node_modules/node-sass
> node scripts/build.js

Building: /home/node-install/node-v13.0.1-linux-x64/bin/node /root/mongodb/my-yapi/vendors/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/node-install/node-v13.0.1-linux-x64/bin/node',
gyp verb cli   '/root/mongodb/my-yapi/vendors/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.0.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.5
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 13.0.1
gyp verb command install [ '13.0.1' ]
gyp verb install input version string "13.0.1"
gyp verb install installing version: 13.0.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 13.0.1
gyp verb ensuring nodedir is created /root/.node-gyp/13.0.1
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/13.0.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '13.0.1' ]
gyp verb install input version string "13.0.1"
gyp verb install installing version: 13.0.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 13.0.1
gyp verb ensuring nodedir is created /root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp/13.0.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '13.0.1' ]
gyp verb remove using node-gyp dir: /root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 13.0.1
gyp verb remove removing development files for version: 13.0.1
gyp WARN install got an error, rolling back install
gyp verb command remove [ '13.0.1' ]
gyp verb remove using node-gyp dir: /root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 13.0.1
gyp verb remove removing development files for version: 13.0.1
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/mongodb/my-yapi/vendors/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 3.10.0-1062.1.1.el7.x86_64
gyp ERR! command "/home/node-install/node-v13.0.1-linux-x64/bin/node" "/root/mongodb/my-yapi/vendors/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /root/mongodb/my-yapi/vendors/node_modules/node-sass
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN markdown-it-include@1.1.1 requires a peer of markdown-it@>=8.4.2 <11.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.3.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-17T09_43_24_088Z-debug.log
internal/modules/cjs/loader.js:803
    throw err;
    ^

Error: Cannot find module 'yapi-plugin-interface-oauth2-token'
Require stack:
- /root/mongodb/my-yapi/vendors/common/plugin.js
- /root/mongodb/my-yapi/vendors/ykit.config.js
- /home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/lib/models/Project.js
- /home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/lib/modules/manager.js
- /home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/lib/cli.js
- /home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/bin/ykit
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:800:15)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getPluginConfig (/root/mongodb/my-yapi/vendors/common/plugin.js:8:20)
    at /root/mongodb/my-yapi/vendors/common/plugin.js:39:22
    at Array.map (<anonymous>)
    at Object.exports.initPlugins (/root/mongodb/my-yapi/vendors/common/plugin.js:33:21)
    at initPlugins (/root/mongodb/my-yapi/vendors/ykit.config.js:42:30)
    at Object.<anonymous> (/root/mongodb/my-yapi/vendors/ykit.config.js:61:1)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/mongodb/my-yapi/vendors/common/plugin.js',
    '/root/mongodb/my-yapi/vendors/ykit.config.js',
    '/home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/lib/models/Project.js',
    '/home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/lib/modules/manager.js',
    '/home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/lib/cli.js',
    '/home/node-install/node-v13.0.1-linux-x64/lib/node_modules/ykit/bin/ykit'
  ]
}
编译客户端成功，请重启服务器
```

**Comment by shouldnotappearcalm** [comment]
前面issue有，先手动装一下node-sass
