### ISSUE TITLE
1.9.2版本，安装插件出现编译错误

### ISSUE THREAD

**Issue by bjtangseng** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#23]
我是用命令行的方式安装Ypai，
nodejs：12.18.3
npm：6.14.6
yapi：1.9.2
node-saas：4.14.1

安装过程中报错：
[error] ./client/components/SchemaTable/index.scss
Module build failed: Error: **Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (72)**
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.0
    at module.exports (/home/admin/yapi/vendors/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/admin/yapi/vendors/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.sassLoader (/home/admin/yapi/vendors/node_modules/sass-loader/lib/loader.js:24:22)
 @ ./client/components/SchemaTable/SchemaTable.js 45:0-23

那个版本的环境出现问题了呢？

**Comment by shouldnotappearcalm** [comment]
你的 `node_modules` 是不是在别的服务器上 `npm install` 的，传输到你这个服务器上来的

**Comment by bjtangseng** [comment]
node sass由于git的问题，npm了数次才成功。
剩余node_modules是通过命令行模式部署。
之前使用Yapi可视化部署后。提示问题和issue #21相同。故使用命令行模式部署

**Comment by shouldnotappearcalm** [comment]
你可以重新 `npm install` 一下，用淘宝的源

**Comment by bjtangseng** [comment]
我一直用的淘宝的源。主要是node_sass需要从git上面下载一个release的包。很慢

**Comment by shouldnotappearcalm** [comment]
现在重装好了么？

**Comment by bjtangseng** [comment]
你所指的重装是重装什么，我刚才尝试使用npm install node-sass。之后安装插件。同样的报错

**Comment by shouldnotappearcalm** [comment]
不行把 `node_modules` 删了，插件卸载掉，再 `npm install`，再安装插件

**Comment by bjtangseng** [comment]
我在尝试一下，有结果回复你

**Comment by bjtangseng** [comment]
我尝试了rm node_modules，然后重新安装node-sass，之后重新安装插件。提示同样的错误。

**Comment by bjtangseng** [comment]
已经成功了，不知道什么是yapi还是什么自动安装了一个4.9.1版本的node-sass。导致引用不正确。4.9的版本不知道nodejs 12

**Comment by shouldnotappearcalm** [comment]
好的
