### ISSUE TITLE
安装失败，怎么解决

### ISSUE THREAD

**Issue by yuhaoz** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#5]
[root@localhost yapi]# yapi plugin --name yapi-plugin-interface-oauth2-token
正在下载插件...

> node-sass@4.9.0 install /hw_apps/yapi/vendors/node_modules/node-sass
> node scripts/install.js

Unable to save binary /hw_apps/yapi/vendors/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/hw_apps/yapi/vendors/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/hw_apps/yapi/vendors/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/hw_apps/yapi/vendors/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/hw_apps/yapi/vendors/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/hw_apps/yapi/vendors/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/hw_apps/yapi/vendors/node_modules/node-sass/vendor' }

**Comment by shouldnotappearcalm** [comment]
你这个看起来像是安装 `node-sass` 模块有问题，但是我自己又找了个全新的虚拟机，装 nodeJS，npm，yapi 和我的插件都没报错，并且启动成功，不知道方不方便约个时间我远程下你电脑看看

**Comment by shouldnotappearcalm** [comment]
先手动安装下 node-sass，再安装插件，`npm install node-sass`
