### ISSUE TITLE
求助link之后缺少多个module问题

### ISSUE THREAD

**Issue by lsw1991abc** [shouldnotappearcalm/yapi-plugin-interface-oauth2-token#9]
在yapi-plugin-interface-oauth2-token中执行
```
npm install node-sass
npm install
npm link
```
在yapi中执行
```
npm link yapi-plugin-interface-oauth2-token
```
执行`npm run dev`时提示以下错误，在token中install node-schedule 之后会有其他的module找不到。最终有个react问题，能否帮忙解答一下，接触前端不多，谢谢
```
[nodemon] starting `node server/app.js dev`
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'node-schedule'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/xxx/yapi-plugin-interface-oauth2-token/utils/syncTokenUtil.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/xxx/yapi-plugin-interface-oauth2-token/controller/controller.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by shouldnotappearcalm** [comment]
为什么要这么使用呢，是要改什么东西么

**Comment by shouldnotappearcalm** [comment]
@lsw1991abc

**Comment by lsw1991abc** [comment]
在获取access token的时候，需要往headers里添加k-v
当前安装运行的，貌似不支持
在url中加basic信息，保存不上   http://username:password@host:port/oauth/token

**Comment by shouldnotappearcalm** [comment]
可以直接我插件的所有代码拷贝到 `exts` 目录下的 `yapi-plugin-test`，然后把 `common/config.js` 把最下面的注释放开，然后 `ykit pack -m`，再使用，比较方便你调试更改代码

**Comment by lsw1991abc** [comment]
好的，谢谢
我试一下
